name: buikd
on:
  push:

jobs:
  build-release:
    name: Build Release Assets
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: i686-pc-windows-gnu
            os: ubuntu-latest
            use-cross: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross || matrix.os == 'ubuntu-latest' }}

      - name: Show sample
        run: du -sh target/${{ matrix.target }}/release 

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: build result
          path: target/${{ matrix.target }}/release/*
